### ISSUE TITLE
Reject from App Store: 4. 3 Design: Spam

### ISSUE THREAD

**Issue by yury** [RxSwiftCommunity/RxMarbles#17]
Guideline 4.3 - Design

This app duplicates the content and functionality of other apps submitted by you or another developer to the App Store, which is considered a form of spam.

Specifically, this app appears to be identical to another app previously submitted under a terminated Apple Developer Program account.

Apps that simply duplicate content or functionality create clutter, diminish the overall experience for the end user, and reduce the ability of developers to market their apps.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Design section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program. 
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

**Comment by yury** [comment]
I tried to find copies of RxMarbles at app store, but couldn't.

**Comment by freak4pc** [comment]
Just appeal that in resolution center. Link them to this repo and mention we’ve been releasing it for a long time and have never faced any issues.

**Comment by yury** [comment]
Yep, already did.
```
Hi,

This app is the original app. It is not duplicate or something. And for sure it is not a spam.
This app is official app that shows how to use RxSwift. This app is developed and maintained as open source project by RxSwift community. 
See the link below
https://github.com/RxSwiftCommunity/RxMarbles

First version of this app was released at feb 2016.
```

**Comment by Vkt0r** [comment]
Very weird last release was 2w ago 🤦‍♂️, they should have a track of that.

**Comment by freak4pc** [comment]
That's Apple for ya 🤷‍♂️

**Comment by yury** [comment]
No news from Apple. 

Submitted appeal.

**Comment by yury** [comment]
Appeal worked. v1.2.4 is in App Store!

**Comment by applereviewer** [comment]
We can solve the problem of 4.3design being rejected, telegram：approvetoappstore
