### ISSUE TITLE
OSX version ?

### ISSUE THREAD

**Issue by plm75** [RxSwiftCommunity/RxMarbles#4]
Would be great to have it as a desktop app too

**Comment by yury** [comment]
I think, playgrounds are better choice on desktop.

**Comment by freak4pc** [comment]
Catalyst time? :]

**Comment by yury** [comment]
Yep :)

**Comment by freak4pc** [comment]
Need help with that or you'll take over it?

**Comment by yury** [comment]
I will try to do that on weekend, but any PR is welcomed!

**Comment by freak4pc** [comment]
Have to say it looks quite good with very few changes. Need to fix up the onboarding and some of the dark mode things. Maybe better to merge #21 first? 

![image](https://user-images.githubusercontent.com/605076/72135137-6fa9e800-338e-11ea-9427-01af586d121a.png)

**Comment by yury** [comment]
Wow!

yep, we should merge #21, but we need to revert `RxMarbles.xcodeproj/project.pbxproj` changes. Actually current version in App Store also has broken dark theme :(

**Comment by freak4pc** [comment]
Yup, probably because it was built in Xcode 11 (iOS 13 SDK)

**Comment by freak4pc** [comment]
😍 

![image](https://user-images.githubusercontent.com/605076/72136801-468b5680-3392-11ea-9aee-0197ebc7c4c8.png)

**Comment by yury** [comment]
Awesome!

**Comment by yury** [comment]
@freak4pc is somewhere public branch, so I can pickup and help you?

**Comment by freak4pc** [comment]
@yury I don't think I pushed the changes, if you want to help with reviewing #22, I'll wrap up my changes and push them onto a branch for you. WDYT ?

**Comment by yury** [comment]
@freak4pc done

**Comment by freak4pc** [comment]
Will push a PR later today

Shai.

**Comment by zeeshankhan** [comment]
Hey guys,
Any plan to push the app on the App Store and catalyst on the Mac App Store?

**Comment by freak4pc** [comment]
Hey, super sorry about this. I totally forgot I never pushed the branch up 🤦 
I plan to take care of this a bit later today or tomorrow (just put this on my todo list).

Cheers.

**Comment by freak4pc** [comment]
I actually forgot about not forgetting, the PR is there for a while.
Let's continue the discussion over there #23
