### ISSUE TITLE
Unable to build RxMarbles.xcworkspace

### ISSUE THREAD

**Issue by rishuagrawal** [RxSwiftCommunity/RxMarbles#5]
I cloned the project successfully and did 'pod install'.
Now when I'm trying to build RxMarbles.xcworkspace I'm getting issues with RxSwift.

Attached the screenshot 
<img width="1440" alt="screen shot 2016-08-17 at 23 07 08" src="https://cloud.githubusercontent.com/assets/20087039/17746799/6eb19164-64cf-11e6-8e36-d3a2b4d9bbba.png">

**Comment by yury** [comment]
Now it should builds without any issues on latest xcode.
