### ISSUE TITLE
SFSafariViewController doesn't open the webpage(s) when app is installed and used for the very first time!

### ISSUE THREAD

**Issue by iamyogish** [RxSwiftCommunity/RxMarbles#9]
The SFSafariViewController doesn't open the webpage when app is installed and used for the the first time, however if we quit the app and reopen it, the SFSafariViewController seems to work fine 🤔 .

**Comment by LightDeveloper** [comment]
Well I debugged the app, this is the error shown when:
` present(safariViewController, animated: true, completion: nil)`
is called:
`Warning: Attempt to present <SFSafariViewController: 0x7c221fe0> on <RxMarbles.OperatorViewController: 0x7ae70ae0> whose view is not in the window hierarchy!
`

**Comment by Vkt0r** [comment]
@LightDeveloper @yury @iamyogish This issue is fixed in the PR #12.
